export const SELECT_VENDOR = "SELECT_VENDOR";
export const RESET_SELECTED_VENDOR = "RESET_SELECTED_VENDOR";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const UPDATE_PRODUCT_IN_CART = "UPDATE_PRODUCT_IN_CART";
export const EMPTY_CART = "EMPTY_CART";
